In [352]:
import pandas as pd
import numpy as np

df_kaggle = pd.read_csv('../data/kaggle_protein_data/pdb_data_seq.csv')
df_kaggle_xray = pd.read_csv('../data/kaggle_protein_data/pdb_data_no_dups.csv')
df_pdb_archive = pd.read_csv('../data/df.csv')

df_k = df_kaggle.copy()
df_xray = df_kaggle_xray.copy()
df = df_pdb_archive.copy()

In [353]:
df_k.head(10)

,structureId,chainId,sequence,residueCount,macromoleculeType
0,100D,A,CCGGCGCCGG,20,DNA/RNA Hybrid
1,100D,B,CCGGCGCCGG,20,DNA/RNA Hybrid
2,101D,A,CGCGAATTCGCG,24,DNA
3,101D,B,CGCGAATTCGCG,24,DNA
4,101M,A,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...,154,Protein
5,102D,A,CGCAAATTTGCG,24,DNA
6,102D,B,CGCAAATTTGCG,24,DNA
7,102L,A,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSE...,165,Protein
8,102M,A,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...,154,Protein
9,103D,A,GTGGAATGGAAC,24,DNA

In [354]:
df_xray.head(5)

,structureId,classification,experimentalTechnique,macromoleculeType,residueCount,resolution,structureMolecularWeight,crystallizationMethod,crystallizationTempK,densityMatthews,densityPercentSol,pdbxDetails,phValue,publicationYear
0,100D,DNA-RNA HYBRID,X-RAY DIFFRACTION,DNA/RNA Hybrid,20,1.90,6360.30,"VAPOR DIFFUSION, HANGING DROP",NaN,1.78,30.89,"pH 7.00, VAPOR DIFFUSION, HANGING DROP",7.0,1994.0
1,101D,DNA,X-RAY DIFFRACTION,DNA,24,2.25,7939.35,NaN,NaN,2.00,38.45,NaN,NaN,1995.0
2,101M,OXYGEN TRANSPORT,X-RAY DIFFRACTION,Protein,154,2.07,18112.80,NaN,NaN,3.09,60.20,"3.0 M AMMONIUM SULFATE, 20 MM TRIS, 1MM EDTA, ...",9.0,1999.0
3,102D,DNA,X-RAY DIFFRACTION,DNA,24,2.20,7637.17,"VAPOR DIFFUSION, SITTING DROP",277.0,2.28,46.06,"pH 7.00, VAPOR DIFFUSION, SITTING DROP, temper...",7.0,1995.0
4,102L,HYDROLASE(O-GLYCOSYL),X-RAY DIFFRACTION,Protein,165,1.74,18926.61,NaN,NaN,2.75,55.28,NaN,NaN,1993.0

In [355]:
df.head(5)

,sequence,pdb_id,mol,length,mol_description
0,CCGGCGCCGG,100d_A,na,10,DNA/RNA (5'-R(*CP*)-D(*CP*GP*GP*CP*GP*CP*CP*GP...
1,CCGGCGCCGG,100d_B,na,10,DNA/RNA (5'-R(*CP*)-D(*CP*GP*GP*CP*GP*CP*CP*GP...
2,CGCGAATTCGCG,101d_A,na,12,DNA (5'-D(*CP*GP*CP*GP*AP*AP*TP*TP*(CBR)P*GP*C...
3,CGCGAATTCGCG,101d_B,na,12,DNA (5'-D(*CP*GP*CP*GP*AP*AP*TP*TP*(CBR)P*GP*C...
4,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...,101m_A,protein,154,MYOGLOBIN

In [356]:
df_id = df['pdb_id'].str.split('_', expand=True)
df_id.head(10)

      0  1
0  100d  A
1  100d  B
2  101d  A
3  101d  B
4  101m  A
5  102d  A
6  102d  B
7  102l  A
8  102m  A
9  103d  A

In [357]:
df['id_pdb'] = df_id[0]
df['subunit'] = df_id[1]
df.head()

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit
0,CCGGCGCCGG,100d_A,na,10,DNA/RNA (5'-R(*CP*)-D(*CP*GP*GP*CP*GP*CP*CP*GP...,100d,A
1,CCGGCGCCGG,100d_B,na,10,DNA/RNA (5'-R(*CP*)-D(*CP*GP*GP*CP*GP*CP*CP*GP...,100d,B
2,CGCGAATTCGCG,101d_A,na,12,DNA (5'-D(*CP*GP*CP*GP*AP*AP*TP*TP*(CBR)P*GP*C...,101d,A
3,CGCGAATTCGCG,101d_B,na,12,DNA (5'-D(*CP*GP*CP*GP*AP*AP*TP*TP*(CBR)P*GP*C...,101d,B
4,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...,101m_A,protein,154,MYOGLOBIN,101m,A

### EXCLUDE NUCLEIC ACIDS:

In [358]:
# Exclude the nucleic acids:
print(f'Full pdb dataset:{df.shape}')
df = df[df['mol']=='protein']
print(f'Excluding DNA/RNA:{df.shape}')

df.head(10)

Full pdb dataset:(767333, 7)
Excluding DNA/RNA:(722336, 7)

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit
4,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...,101m_A,protein,154,MYOGLOBIN,101m,A
7,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSE...,102l_A,protein,165,T4 LYSOZYME,102l,A
8,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...,102m_A,protein,154,MYOGLOBIN,102m,A
11,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNSLDAAK...,103l_A,protein,167,T4 LYSOZYME,103l,A
12,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...,103m_A,protein,154,MYOGLOBIN,103m,A
15,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSAA...,104l_A,protein,166,T4 LYSOZYME,104l,A
16,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSAA...,104l_B,protein,166,T4 LYSOZYME,104l,B
17,VLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRF...,104m_A,protein,153,MYOGLOBIN,104m,A
22,VLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRF...,105m_A,protein,153,MYOGLOBIN,105m,A
27,MVLSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDR...,106m_A,protein,154,MYOGLOBIN,106m,A

### MISSING VALUES:

In [359]:
df.isna().sum()

sequence            0
pdb_id              0
mol                 0
length              0
mol_description    24
id_pdb              0
subunit             0
dtype: int64

In [360]:
df_nan = df[df['mol_description'].isna()]
df_nan

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit
9642,TVAYIAIGSNLASPLEQVNAALKALGDIPESHILTVSSFYRTPPLG...,1dy3_A,protein,158,NaN,1dy3,A
45416,MLVVPAIDLFRGKVARMIKGRKENTIFYEKDPVELVEKLIEEGFTL...,1qo2_A,protein,241,NaN,1qo2,A
45417,MLVVPAIDLFRGKVARMIKGRKENTIFYEKDPVELVEKLIEEGFTL...,1qo2_B,protein,241,NaN,1qo2,B
124262,ELSENFKKLMKYPYRPCTCTRCIEEQRVSAWFDERFNRSMQPLLTA...,2wnb_A,protein,298,NaN,2wnb,A
336577,MIIPALNLIDGTVVRLHQGDYARQRDYGNDPLPRLQDYAAQGAGVL...,5a5w_A,protein,253,NaN,5a5w,A
336882,ANSVQQQLEALEKSSGGRLGVALINTADNSQILYRADERFAMCSTS...,5a91_A,protein,262,NaN,5a91,A
337299,MIIPALDLIGGTVVRVVRLHQGDYARLRDYGNDPLPRLQDYAAQGA...,5ac6_A,protein,256,NaN,5ac6,A
337300,MIIPALNLIGGTVVRVVRLHQGDYARQRDYGNDPLPRLQDYAAQGA...,5ac7_A,protein,256,NaN,5ac7,A
337301,MIIPALNLIGGTVVRVVRLHQGDYARQRDYGNDPLPRLQDYAAQGA...,5ac7_B,protein,256,NaN,5ac7,B
337302,MIIPALDLIGGTVVRVVRLHQGDYARQRDYGNDPLPRLQDYAAQGA...,5ac8_A,protein,256,NaN,5ac8,A
337917,MIIPALDLIDGTVVRLHQGDYARQRDYGNDPLPRLQDYAAQGAGVL...,5ahe_A,protein,253,NaN,5ahe,A
337918,MIIPALNLIDGTVVRLHQGDYARQRDYGNDPLPRLQDYAAQGAGVL...,5ahf_A,protein,253,NaN,5ahf,A
359037,MKLSGVELRRVQMPLVAPFRTSFGTQSVRELLLLRAVTPAGEGWGE...,5fjo_A,protein,368,NaN,5fjo,A
359038,MKLSGVELRRVQMPLVAPFRTSFGTQSVRELLLLRAVTPAGEGWGE...,5fjo_B,protein,368,NaN,5fjo,B
360982,MIIPALDLIGGTVVRVVRLHQGDYARQRDYGNDPLPRLQDYAAQGA...,5g1t_A,protein,256,NaN,5g1t,A
361000,MIIPALDLIGGTVVRVMRLHQGDYARLRDYGNDPLPRLQDYAAQGA...,5g1y_A,protein,256,NaN,5g1y,A
361053,MIIPALDLIDGTVVRLHQGDYARQRDYGNDPLPRLQDYAAQGAGVL...,5g2h_A,protein,253,NaN,5g2h,A
361054,MIIPALDLIDGTVVRVVRLHQGDYARQRDYGNDPLPRLQDYAAQGA...,5g2i_A,protein,256,NaN,5g2i,A
361083,MIIPALDLIGGTVVRLHQGDYARQRDYGNDPLPRLQDYAAQGAGVL...,5g2w_A,protein,253,NaN,5g2w,A
361157,MGSSHHHHHHSSGLVPRGSHMQGSLMLDIGGTWLTAEDRQILRHPE...,5g3r_A,protein,352,NaN,5g3r,A
361158,MGSSHHHHHHSSGLVPRGSHMQGSLMLDIGGTWLTAEDRQILRHPE...,5g3r_B,protein,352,NaN,5g3r,B
361201,MIIPALDLIGGTVVRVVRLHQGDYARLRDYGNDPLPRLQDYAAQGA...,5g4e_A,protein,256,NaN,5g4e,A
361202,MIIPALDLIGGTVVRVVRLHQGDYARLRDYGNDPLPRLQDYAAQGA...,5g4e_B,protein,256,NaN,5g4e,B
361300,MIIPALDLIGGTVVRLHQGDYARQRDYGNDPLPRLQDYAAQGAGVL...,5g5i_A,protein,253,NaN,5g5i,A

In [361]:
prot_ids = list(df_nan['id_pdb'].unique())
prot_ids

['1dy3',
 '1qo2',
 '2wnb',
 '5a5w',
 '5a91',
 '5ac6',
 '5ac7',
 '5ac8',
 '5ahe',
 '5ahf',
 '5fjo',
 '5g1t',
 '5g1y',
 '5g2h',
 '5g2i',
 '5g2w',
 '5g3r',
 '5g4e',
 '5g5i']

>NOTE: I found the following classification labels by manually entering the protein id into the pdb search bar.  This was feasable only because there were only 20 missing labels, but figuring out how to use the pdb api for this would be idea in future applications.

In [362]:
missing_lables = {
      '1dy3': 'PYROPHOSPHORYLASE'
    , '1qo2': 'ISOMERASE'
    , '2wnb': 'TRANSFERASE'
    , '5a5w': 'ISOMERASE'
    , '5a91': 'HYDROLASE'
    , '5ac6': 'ISOMERASE'
    , '5ac7': 'ISOMERASE'
    , '5ac8': 'ISOMERASE'
    , '5ahe': 'ISOMERASE'
    , '5ahf': 'ISOMERASE'
    , '5fjo': 'LYASE'
    , '5g1t': 'ISOMERASE'
    , '5g1y': 'ISOMERASE'
    , '5g2h': 'ISOMERASE'
    , '5g2i': 'ISOMERASE'
    , '5g2w': 'ISOMERASE'
    , '5g3r': 'HYDROLASE'
    , '5g4e': 'ISOMERASE'
    , '5g5i': 'ISOMERASE'
}

In [363]:
df['mol_description'] = df['mol_description'].fillna(df['id_pdb'].map(missing_lables))
df.isna().sum()

sequence           0
pdb_id             0
mol                0
length             0
mol_description    0
id_pdb             0
subunit            0
dtype: int64

In [364]:
df['mol_description'].nunique()

81534

## TARGET VARIABLE REFINEMENT:

In [311]:
df['label'] = df['mol_description']

In [312]:
df['label'].value_counts().head(10)

Capsid protein             2672
Spike glycoprotein         2623
capsid protein             2623
coat protein               2526
Capsid protein VP1         2151
Major capsid protein       1983
Uncharacterized protein    1981
Beta-2-microglobulin       1948
Coat protein               1640
Beta-lactamase             1400
Name: label, dtype: int64

In [313]:
df['label'] = df['label'].str.upper()
df['label'].value_counts().head(20)

CAPSID PROTEIN                                                     5335
COAT PROTEIN                                                       4587
SPIKE GLYCOPROTEIN                                                 2634
UNCHARACTERIZED PROTEIN                                            2177
CAPSID PROTEIN VP1                                                 2158
MAJOR CAPSID PROTEIN                                               2115
BETA-2-MICROGLOBULIN                                               2091
BETA-LACTAMASE                                                     1532
HEMAGGLUTININ                                                      1321
ATP-DEPENDENT CLP PROTEASE PROTEOLYTIC SUBUNIT                     1288
HISTONE H4                                                         1276
CAMP AND CAMP-INHIBITED CGMP 3',5'-CYCLIC PHOSPHODIESTERASE 10A    1151
B-PHYCOERYTHRIN BETA CHAIN                                         1106
30S RIBOSOMAL PROTEIN S10                                          1101
30S RIBOSOMAL PROTEIN S12                                          1100
30S RIBOSOMAL PROTEIN S15                                          1099
30S RIBOSOMAL PROTEIN S6                                           1096
30S RIBOSOMAL PROTEIN S11                                          1093
30S RIBOSOMAL PROTEIN S8                                           1091
30S RIBOSOMAL PROTEIN S5                                           1087
Name: label, dtype: int64

In [314]:
df_enzymes = df[df['label'].str.contains('ase', case=False)]
print(f'df_enzymes.shape: {df_enzymes.shape}')
print(f'df_enzymes.label.nunique(): {df_enzymes["label"].nunique()}')
display(df_enzymes.head(5))

df_enzymes.shape: (242823, 8)
df_enzymes.label.nunique(): 19200

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
40,PPYTVVYFPVRGRCAALRMLLADQGQSWKEEVVTVETWQEGSLKAS...,10gs_A,protein,209,GLUTATHIONE S-TRANSFERASE P1-1,10gs,A,GLUTATHIONE S-TRANSFERASE P1-1
41,PPYTVVYFPVRGRCAALRMLLADQGQSWKEEVVTVETWQEGSLKAS...,10gs_B,protein,209,GLUTATHIONE S-TRANSFERASE P1-1,10gs,B,GLUTATHIONE S-TRANSFERASE P1-1
44,MIEIKDKQLTGLRFIDLFAGLGGFRLALESCGAECVYSNEWDKYAQ...,10mh_A,protein,327,PROTEIN (CYTOSINE-SPECIFIC METHYLTRANSFERASE H...,10mh,A,PROTEIN (CYTOSINE-SPECIFIC METHYLTRANSFERASE H...
67,TYTTRQIGAKNTLEYKVYIEKDGKPVSAFHDIPLYADKENNIFNMV...,117e_A,protein,286,PROTEIN (INORGANIC PYROPHOSPHATASE),117e,A,PROTEIN (INORGANIC PYROPHOSPHATASE)
68,TYTTRQIGAKNTLEYKVYIEKDGKPVSAFHDIPLYADKENNIFNMV...,117e_B,protein,286,PROTEIN (INORGANIC PYROPHOSPHATASE),117e,B,PROTEIN (INORGANIC PYROPHOSPHATASE)

In [315]:
df_enzymes.label.value_counts().head(20)

BETA-LACTAMASE                                                                                               1532
ATP-DEPENDENT CLP PROTEASE PROTEOLYTIC SUBUNIT                                                               1288
CAMP AND CAMP-INHIBITED CGMP 3',5'-CYCLIC PHOSPHODIESTERASE 10A                                              1151
6,7-DIMETHYL-8-RIBITYLLUMAZINE SYNTHASE                                                                      1045
DNA-DIRECTED RNA POLYMERASE SUBUNIT ALPHA                                                                    1008
3C-LIKE PROTEINASE                                                                                            965
ANTITERMINATION PROTEIN N,6,7-DIMETHYL-8-RIBITYLLUMAZINE SYNTHASE,6,7-DIMETHYL-8-RIBITYLLUMAZINE SYNTHASE     960
CARBONIC ANHYDRASE 2                                                                                          956
PROTEASE                                                                                                      916
ATP SYNTHASE SUBUNIT C                                                                                        756
BETA-SECRETASE 1                                                                                              692
NITRIC OXIDE SYNTHASE, BRAIN                                                                                  671
DIHYDROFOLATE REDUCTASE                                                                                       659
NUCLEOSIDE DIPHOSPHATE KINASE                                                                                 645
3-DEHYDROQUINATE DEHYDRATASE                                                                                  618
ATP SYNTHASE SUBUNIT BETA                                                                                     613
SUPEROXIDE DISMUTASE [CU-ZN]                                                                                  608
DNA-DIRECTED RNA POLYMERASE SUBUNIT BETA                                                                      602
INTEGRASE                                                                                                     578
ATP SYNTHASE SUBUNIT ALPHA                                                                                    568
Name: label, dtype: int64

In [329]:
def contains_sub_text(df, column_name, sub_text, case=False):
    df = df[df[column_name].str.contains(sub_text, case=case)]
    print(f'df.shape: {df.shape}')
    print(f'df.{column_name}.nunique(): {df[column_name].nunique()}')
    display(df.head(5))
    display(df[column_name].value_counts().head(10))
    return df

def change_label(df, column_name, new_label, sub_text=False, case=False):
    if sub_text == False:
        sub_text = new_label
    df.loc[df[column_name].str.contains(sub_text, case=False), column_name] = new_label
    return df

In [317]:
df_protease = contains_sub_text(df_enzymes, 'label', 'protease')

df.shape: (7354, 8)
df.label.nunique(): 544

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
607,PQITLWKRPLVTIKIGGQLKEALLDTGADDTVIEEMSLPGRWKPKM...,1a30_A,protein,99,HIV-1 PROTEASE,1a30,A,HIV-1 PROTEASE
608,PQITLWKRPLVTIKIGGQLKEALLDTGADDTVIEEMSLPGRWKPKM...,1a30_B,protein,99,HIV-1 PROTEASE,1a30,B,HIV-1 PROTEASE
1014,PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKM...,1a8g_A,protein,99,HIV-1 PROTEASE,1a8g,A,HIV-1 PROTEASE
1015,PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKM...,1a8g_B,protein,99,HIV-1 PROTEASE,1a8g,B,HIV-1 PROTEASE
1020,PQITLWKRPLVTIKIGGQLKEALLDTGADDTVIEEMSLPGRWKPKM...,1a8k_A,protein,99,HIV PROTEASE,1a8k,A,HIV PROTEASE

ATP-DEPENDENT CLP PROTEASE PROTEOLYTIC SUBUNIT         1288
PROTEASE                                                916
HIV-1 PROTEASE                                          408
ATP-DEPENDENT CLP PROTEASE ATP-BINDING SUBUNIT CLPX     158
LON PROTEASE HOMOLOG, MITOCHONDRIAL                     122
ATP-DEPENDENT CLP PROTEASE PROTEOLYTIC SUBUNIT 1        112
NS3 PROTEASE                                            111
LON PROTEASE                                            104
PROTEASE RETROPEPSIN                                    102
ATP-DEPENDENT ZINC METALLOPROTEASE FTSH                  94
Name: label, dtype: int64

In [318]:
df_protease_hiv = contains_sub_text(df_enzymes, 'label', 'hiv-1 protease')

df.shape: (481, 8)
df.label.nunique(): 26

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
607,PQITLWKRPLVTIKIGGQLKEALLDTGADDTVIEEMSLPGRWKPKM...,1a30_A,protein,99,HIV-1 PROTEASE,1a30,A,HIV-1 PROTEASE
608,PQITLWKRPLVTIKIGGQLKEALLDTGADDTVIEEMSLPGRWKPKM...,1a30_B,protein,99,HIV-1 PROTEASE,1a30,B,HIV-1 PROTEASE
1014,PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKM...,1a8g_A,protein,99,HIV-1 PROTEASE,1a8g,A,HIV-1 PROTEASE
1015,PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKM...,1a8g_B,protein,99,HIV-1 PROTEASE,1a8g,B,HIV-1 PROTEASE
1122,PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMSLPGRWKPKM...,1a9m_A,protein,99,HIV-1 PROTEASE,1a9m,A,HIV-1 PROTEASE

HIV-1 PROTEASE                                             408
PROTEIN (HIV-1 PROTEASE)                                    12
MDR HIV-1 PROTEASE                                          10
CHEMICAL ANALOGUE HIV-1 PROTEASE                             4
MULTIDRUG-RESISTANT CLINICAL ISOLATE 769 HIV-1 PROTEASE      4
HIV-1 PROTEASE PR-S17                                        4
HIV-1 PROTEASE (RETROPEPSIN)                                 4
HIV-1 PROTEASE, FRAGMENT                                     3
UNLIGANDED HIV-1 PROTEASE                                    3
[GLY51;AIB51'] 'COVALENT DIMER' HIV-1 PROTEASE               2
Name: label, dtype: int64

In [319]:
list(df_protease_hiv.label.unique())

['HIV-1 PROTEASE',
 'PROTEIN (HIV-1 PROTEASE)',
 'HIV-1 PROTEASE (RETROPEPSIN)',
 'UNLIGANDED HIV-1 PROTEASE',
 'EPITOPE PEPTIDE CORRESPONDING TO N-TERMINUS OF HIV-1 PROTEASE',
 'HIV-1 PROTEASE PEPTIDE',
 'COVALENT DIMER HIV-1 PROTEASE',
 'CHEMICAL ANALOGUE HIV-1 PROTEASE',
 "COVALENT DIMER [L-ALA51, D-ALA51'] HIV-1 PROTEASE",
 "COVALENT DIMER [L-ALA51,D-ALA51'] HIV-1 PROTEASE",
 "[L-ALA51/51']HIV-1 PROTEASE",
 "[D-ALA51/51']HIV-1 PROTEASE",
 "[AIB51/51']HIV-1 PROTEASE",
 "'COVALENT DIMER' [GLY51/D-ALA51'] HIV-1 PROTEASE",
 "[GLY51;AIB51'] 'COVALENT DIMER' HIV-1 PROTEASE",
 '[D25N]HIV-1 PROTEASE',
 "[L-ALA51;GLY51']HIV-1 PROTEASE",
 'MULTI-DRUG RESISTANT HIV-1 PROTEASE',
 'MDR HIV-1 PROTEASE',
 'MULTIDRUG-RESISTANT CLINICAL ISOLATE 769 HIV-1 PROTEASE',
 'WILD-TYPE HIV-1 PROTEASE DIMER',
 'HIV-1 PROTEASE, FRAGMENT',
 'MDR769 HIV-1 PROTEASE',
 'A17 HIV-1 PROTEASE',
 'PHAGE DISPLAY-OPTIMIZED HIV-1 PROTEASE SUBSTRATE',
 'HIV-1 PROTEASE PR-S17']

In [331]:
contains_sub_text(df, 'label', 'RETROPEPSIN')

df.shape: (0, 8)
df.label.nunique(): 0

Empty DataFrame
Columns: [sequence, pdb_id, mol, length, mol_description, id_pdb, subunit, label]
Index: []

Series([], Name: label, dtype: int64)

Empty DataFrame
Columns: [sequence, pdb_id, mol, length, mol_description, id_pdb, subunit, label]
Index: []

In [332]:
df = change_label(df, 'label', 'HIV-1 PROTEASE', sub_text='RETROPEPSIN')
df_enzymes = change_label(df_enzymes, 'label', 'HIV-1 PROTEASE', sub_text='RETROPEPSIN')
df_protease = change_label(df_protease, 'label', 'HIV-1 PROTEASE', sub_text='RETROPEPSIN')

In [337]:
df = change_label(df, 'label', 'HIV-1 PROTEASE', sub_text='HUMAN IMMUNODEFICIENCY')
df_enzymes = change_label(df_enzymes, 'label', 'HIV-1 PROTEASE', sub_text='HUMAN IMMUNODEFICIENCY')
df_protease = change_label(df_protease, 'label', 'HIV-1 PROTEASE', sub_text='HUMAN IMMUNODEFICIENCY')

In [339]:
df = change_label(df, 'label', 'HIV PROTEASE', sub_text='HIV')
df_enzymes = change_label(df_enzymes, 'label', 'HIV PROTEASE', sub_text='HIV')
df_protease = change_label(df_protease, 'label', 'HIV PROTEASE', sub_text='HIV')

In [320]:
df = change_label(df, 'label', 'HIV-1 PROTEASE')
df_enzymes = change_label(df_enzymes, 'label', 'HIV-1 PROTEASE')
df_protease = change_label(df_protease, 'label', 'HIV-1 PROTEASE')

In [338]:
df = change_label(df, 'label', 'HELICASE', sub_text='HELICASE')
df_enzymes = change_label(df_enzymes, 'label', 'HELICASE', sub_text='HELICASE')
df_protease = change_label(df_protease, 'label', 'HELICASE', sub_text='HELICASE')

In [341]:
# HEAT SHOCK PROTEASES
df = change_label(df, 'label', 'HEAT SHOCK PROTEASE', sub_text='ATP-DEPENDENT HSL')
df_enzymes = change_label(df_enzymes, 'label', 'HEAT SHOCK PROTEASE', sub_text='ATP-DEPENDENT HSL')
df_protease = change_label(df_protease, 'label', 'HEAT SHOCK PROTEASE', sub_text='ATP-DEPENDENT HSL')

df = change_label(df, 'label', 'HEAT SHOCK PROTEASE', sub_text='HSLV')
df_enzymes = change_label(df_enzymes, 'label', 'HEAT SHOCK PROTEASE', sub_text='HSLV')
df_protease = change_label(df_protease, 'label', 'HEAT SHOCK PROTEASE', sub_text='HSLV')

df = change_label(df, 'label', 'HEAT SHOCK PROTEASE', sub_text='HTRA')
df_enzymes = change_label(df_enzymes, 'label', 'HEAT SHOCK PROTEASE', sub_text='HTRA')
df_protease = change_label(df_protease, 'label', 'HEAT SHOCK PROTEASE', sub_text='HTRA')

In [342]:
# ALPHA-LYTIC PROTEASES
df = change_label(df, 'label', 'ALPHA-LYTIC PROTEASE', sub_text='ALPHA')
df_enzymes = change_label(df_enzymes, 'label', 'ALPHA-LYTIC PROTEASE', sub_text='ALPHA')
df_protease = change_label(df_protease, 'label', 'ALPHA-LYTIC PROTEASE', sub_text='ALPHA')

df = change_label(df, 'label', 'ALPHA-LYTIC PROTEASE', sub_text='ALHPA')
df_enzymes = change_label(df_enzymes, 'label', 'ALPHA-LYTIC PROTEASE', sub_text='ALHPA')
df_protease = change_label(df_protease, 'label', 'ALPHA-LYTIC PROTEASE', sub_text='ALHPA')

In [343]:
# TRICORN PROTEASES
df = change_label(df, 'label', 'TRICORN PROTEASE', sub_text='TRICORN')
df_enzymes = change_label(df_enzymes, 'label', 'TRICORN PROTEASE', sub_text='TRICORN')
df_protease = change_label(df_protease, 'label', 'TRICORN PROTEASE', sub_text='TRICORN')

In [344]:
'PROTEASE INHIBITOR'
protease_inh = contains_sub_text(df_protease, 'label', 'PROTEASE INHIBITOR')

df.shape: (124, 8)
df.label.nunique(): 1

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
3771,SAGTSCVPGWAIPHNPLPSCRWYVTSRTCGIGPRLPWPELKRRCCR...,1bea_A,protein,127,BIFUNCTIONAL AMYLASE/SERINE PROTEASE INHIBITOR,1bea,A,PROTEASE INHIBITOR
3818,MARIPMASAGTSCVPGWAIPHNPLPSCRWYVTSRTCGIGPRLPWPE...,1bfa_A,protein,134,BIFUNCTIONAL AMYLASE/SERINE PROTEASE INHIBITOR,1bfa,A,PROTEASE INHIBITOR
5846,EVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTE...,1ca0_D,protein,54,PROTEASE INHIBITOR DOMAIN OF ALZHEIMER'S AMYLO...,1ca0,D,PROTEASE INHIBITOR
5847,EVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFDTE...,1ca0_I,protein,54,PROTEASE INHIBITOR DOMAIN OF ALZHEIMER'S AMYLO...,1ca0,I,PROTEASE INHIBITOR
8502,ADQLLRKKRRIFIHSVGAGTINALLDCLLEDEVISQEDMNKVRDEN...,1dgn_A,protein,89,ICEBERG (PROTEASE INHIBITOR),1dgn,A,PROTEASE INHIBITOR

PROTEASE INHIBITOR    124
Name: label, dtype: int64

In [345]:
df = change_label(df, 'label', 'PROTEASE INHIBITOR')
df_enzymes = change_label(df_enzymes, 'label', 'PROTEASE INHIBITOR')
df_protease = change_label(df_protease, 'label', 'PROTEASE INHIBITOR')

In [349]:
# SERINE PROTEASES
df = change_label(df, 'label', 'SERINE PROTEASE', sub_text='SERINE')
df_enzymes = change_label(df_enzymes, 'label', 'SERINE PROTEASE', sub_text='SERINE')
df_protease = change_label(df_protease, 'label', 'SERINE PROTEASE', sub_text='SERINE')

df = change_label(df, 'label', 'SERINE PROTEASE', sub_text='NS3')
df_enzymes = change_label(df_enzymes, 'label', 'SERINE PROTEASE', sub_text='NS3')
df_protease = change_label(df_protease, 'label', 'SERINE PROTEASE', sub_text='NS3')

df = change_label(df, 'label', 'SERINE PROTEASE', sub_text='DEGS')
df_enzymes = change_label(df_enzymes, 'label', 'SERINE PROTEASE', sub_text='DEGS')
df_protease = change_label(df_protease, 'label', 'SERINE PROTEASE', sub_text='DEGS')

df = change_label(df, 'label', 'SERINE PROTEASE', sub_text='HELICASE')
df_enzymes = change_label(df_enzymes, 'label', 'SERINE PROTEASE', sub_text='HELICASE')
df_protease = change_label(df_protease, 'label', 'SERINE PROTEASE', sub_text='HELICASE')

df = change_label(df, 'label', 'SERINE PROTEASE', sub_text='CLP')
df_enzymes = change_label(df_enzymes, 'label', 'SERINE PROTEASE', sub_text='CLP')
df_protease = change_label(df_protease, 'label', 'SERINE PROTEASE', sub_text='CLP')

df = change_label(df, 'label', 'SERINE PROTEASE', sub_text='PROTEASE LA')
df_enzymes = change_label(df_enzymes, 'label', 'SERINE PROTEASE', sub_text='PROTEASE LA')
df_protease = change_label(df_protease, 'label', 'SERINE PROTEASE', sub_text='PROTEASE LA')

In [365]:
df_protease.shape

(7354, 8)

In [350]:
# CYSTEINE PROTEASES
df = change_label(df, 'label', 'CYSTEINE PROTEASE', sub_text='CYSTEINE')
df_enzymes = change_label(df_enzymes, 'label', 'CYSTEINE PROTEASE', sub_text='CYSTEINE')
df_protease = change_label(df_protease, 'label', 'CYSTEINE PROTEASE', sub_text='CYSTEINE')

df = change_label(df, 'label', 'CYSTEINE PROTEASE', sub_text='SENTRIN')
df_enzymes = change_label(df_enzymes, 'label', 'CYSTEINE PROTEASE', sub_text='SENTRIN')
df_protease = change_label(df_protease, 'label', 'CYSTEINE PROTEASE', sub_text='SENTRIN')

In [351]:
# HIV-ANALOG PROTEASES
df = change_label(df, 'label', 'HIV-ANALOG PROTEASE', sub_text='SIV')
df_enzymes = change_label(df_enzymes, 'label', 'HIV-ANALOG PROTEASE', sub_text='SIV')
df_protease = change_label(df_protease, 'label', 'HIV-ANALOG PROTEASE', sub_text='SIV')

df = change_label(df, 'label', 'HIV-ANALOG PROTEASE', sub_text='FELINE')
df_enzymes = change_label(df_enzymes, 'label', 'HIV-ANALOG PROTEASE', sub_text='FELINE')
df_protease = change_label(df_protease, 'label', 'HIV-ANALOG PROTEASE', sub_text='FELINE')

In [347]:
df_protease.label.value_counts().tail(20)

V8 PROTEASE                                                                             1
HYDROGENASE MATURATION PROTEASE HYCI                                                    1
INACTIVE ZYMOGEN C11 PROTEASE                                                           1
NFKB-P65-DEGRADING ZINC PROTEASE FAMILY PROTEIN                                         1
PUTATIVE GERMINATION-SPECIFIC PROTEASE                                                  1
EQUINE INFECTIOUS ANEMIA VIRUS PROTEASE                                                 1
PUTATIVE S41 PROTEASE                                                                   1
RHOMBOID INTRAMEMBRANE PROTEASE                                                         1
SEVERE ACUTE RESPIRATORY SYNDROME CORONAVIRUS 3C LIKE PROTEASE                          1
HEPATITIS A VIRUS PROTEASE 3C                                                           1
HEPATITIS A PROTEASE 3C                                                                 1
ELASTINOLYTIC METALLOPROTEASE                                                           1
FACTOR X-LIKE PROTEASE                                                                  1
PUTATIVE ZINC METALLOPROTEASE AQ_1964,PUTATIVE ZINC METALLOPROTEASE AQ_1964             1
ZINC PROTEASE                                                                           1
SARS-COV MAIN PROTEASE                                                                  1
ULP1-LIKE SUMO PROTEASE                                                                 1
RHOMBOID PROTEASE GLPG 1                                                                1
PROTEIN (FELINE IMMUNODEFICIENCY VIRUS PROTEASE)                                        1
PDZ TANDEM FRAGMENT OF A. AEOLICUS SITE-2 PROTEASE HOMOLOG WITH THE PA TAG INSERTION    1
Name: label, dtype: int64

In [269]:
df = df[df.where(~df.isin(df_enzymes)).notna()]
df.dropna(inplace=True)
df['label'].value_counts().head(20)

RIBOSOMAL                       84768
HEAVY CHAIN                     11495
LIGHT CHAIN                     10834
CAPSID PROTEIN                   5335
COAT PROTEIN                     4587
SPIKE GLYCOPROTEIN               2634
UNCHARACTERIZED PROTEIN          2177
CAPSID PROTEIN VP1               2158
MAJOR CAPSID PROTEIN             2115
BETA-2-MICROGLOBULIN             2091
HEMAGGLUTININ                    1321
HISTONE H4                       1276
B-PHYCOERYTHRIN BETA CHAIN       1106
PHYCOERYTHRIN ALPHA SUBUNIT      1044
LYSOZYME C                       1013
NON-STRUCTURAL PROTEIN 3          984
ACTIN, ALPHA SKELETAL MUSCLE      968
MICROCOMPARTMENTS PROTEIN         931
FERRITIN                          914
TRANSTHYRETIN                     893
Name: label, dtype: int64

In [234]:
df_ribosomes = df[df['label'].str.contains('RIBOSOMAL')]
print(f'df_ribosomes.shape: {df_ribosomes.shape}')
print(f'df_ribosomes.label.nunique(): {df_ribosomes["label"].nunique()}')
display(df_ribosomes.head(5))

df_Ab = df[df['label'].str.contains('HEAVY CHAIN', 'LIGHT CHAIN')]
print(f'df_Ab.shape: {df_Ab.shape}')
print(f'df_Ab.label.nunique(): {df_Ab["label"].nunique()}')
display(df_Ab.head(5))

df_ribosomes.shape: (84768, 8)
df_ribosomes.label.nunique(): 1970

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
613,ALTQERKREIIEQFKVHENDTGSPEVQIAILTEQINNLNEHLRVHK...,1a32_A,protein,88,RIBOSOMAL PROTEIN S15,1a32,A,RIBOSOMAL PROTEIN S15
1196,PITKEEKQKVIQEFARFPGDTGSTEVQVALLTLRINRLSEHLKVHK...,1ab3_A,protein,88,RIBOSOMAL RNA BINDING PROTEIN S15,1ab3,A,RIBOSOMAL RNA BINDING PROTEIN S15
1259,MTFITKTPPAAVLLKKAAGIESGSGEPNRNKVATIKRDKVREIAEL...,1aci_A,protein,76,L11 RIBOSOMAL PROTEIN,1aci,A,L11 RIBOSOMAL PROTEIN
1282,PKHGKRYRALLEKVDPNKIYTIDEAAHLVKELATAKFDETVEVHAK...,1ad2_A,protein,228,RIBOSOMAL PROTEIN L1,1ad2,A,RIBOSOMAL PROTEIN L1
1911,TDPIADMLTRIRNATRVYKESTDVPASRFKEEILRILAREGFIKGY...,1an7_A,protein,136,RIBOSOMAL PROTEIN S8,1an7,A,RIBOSOMAL PROTEIN S8

df_Ab.shape: (11517, 8)
df_Ab.label.nunique(): 3158

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
112,EVQLQQSGAEVVRSGASVKLSCTASGFNIKDYYIHWVKQRPEKGLE...,12e8_H,protein,221,IGG1-KAPPA 2E8 FAB (HEAVY CHAIN),12e8,H,IGG1-KAPPA 2E8 FAB (HEAVY CHAIN)
113,EVQLQQSGAEVVRSGASVKLSCTASGFNIKDYYIHWVKQRPEKGLE...,12e8_P,protein,221,IGG1-KAPPA 2E8 FAB (HEAVY CHAIN),12e8,P,IGG1-KAPPA 2E8 FAB (HEAVY CHAIN)
212,EVQLQQSGAELVKPGASVKLSCTASGFNIKDTYMHWVKQKPEQGLE...,15c8_H,protein,217,IGG 5C8 FAB (HEAVY CHAIN),15c8,H,IGG 5C8 FAB (HEAVY CHAIN)
439,EVQLQESDAELVKPGASVKISCKASGYTFTDHVIHWVKQKPEQGLE...,1a0q_H,protein,217,29G11 FAB (HEAVY CHAIN),1a0q,H,29G11 FAB (HEAVY CHAIN)
463,QVQLQQSGAELVKPGASVRMSCKASGYTFTNYNMYWVKQSPGQGLE...,1a14_H,protein,120,NC10 FV (HEAVY CHAIN),1a14,H,NC10 FV (HEAVY CHAIN)

Reviewing the above:
- trial changing all ribosomal complex subunit labels to "RIBOSOMAL"
- Because there are so many antibody chains, trial relabeling to "HEAVY CHAIN" and "LIGHT CHAIN" separately

In [239]:
df.loc[df['label'].str.contains('LIGHT CHAIN', case=False), 'label'] = 'LIGHT CHAIN'
df.loc[df['label'].str.contains('HEAVY CHAIN', case=False), 'label'] = 'HEAVY CHAIN'
df.loc[df['label'].str.contains('RIBOSOMAL', case=False), 'label'] = 'RIBOSOMAL'

df['label'].value_counts().head(20)

RIBOSOMAL                                                          84768
HEAVY CHAIN                                                        11495
LIGHT CHAIN                                                        10834
CAPSID PROTEIN                                                      5335
COAT PROTEIN                                                        4587
SPIKE GLYCOPROTEIN                                                  2634
UNCHARACTERIZED PROTEIN                                             2177
CAPSID PROTEIN VP1                                                  2158
MAJOR CAPSID PROTEIN                                                2115
BETA-2-MICROGLOBULIN                                                2091
BETA-LACTAMASE                                                      1532
HEMAGGLUTININ                                                       1321
ATP-DEPENDENT CLP PROTEASE PROTEOLYTIC SUBUNIT                      1288
HISTONE H4                                                          1276
CAMP AND CAMP-INHIBITED CGMP 3',5'-CYCLIC PHOSPHODIESTERASE 10A     1151
B-PHYCOERYTHRIN BETA CHAIN                                          1106
6,7-DIMETHYL-8-RIBITYLLUMAZINE SYNTHASE                             1045
PHYCOERYTHRIN ALPHA SUBUNIT                                         1044
LYSOZYME C                                                          1013
DNA-DIRECTED RNA POLYMERASE SUBUNIT ALPHA                           1008
Name: label, dtype: int64

In [275]:
def contains_sub_text(df, column_name, sub_text, case=False):
    df = df[df[column_name].str.contains(sub_text, case=case)]
    print(f'df.shape: {df.shape}')
    print(f'df.{column_name}.nunique(): {df[column_name].nunique()}')
    display(df.head(5))
    display(df[column_name].value_counts().head(20))
    return df

def change_label(df, column_name, new_label, case=False):
    df.loc[df[column_name].str.contains(new_label, case=False), column_name] = new_label
    return df

In [277]:
def change_label(df, column_name, new_label, case=False):
    df.loc[df[column_name].str.contains(new_label, case=False), column_name] = new_label
    return df

In [276]:
df_lysozyme = contains_sub_text(df, 'label', 'lysozyme')

df.shape: (2473, 8)
df.label.nunique(): 103

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
7,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAAKSE...,102l_A,protein,165.0,T4 LYSOZYME,102l,A,T4 LYSOZYME
11,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNSLDAAK...,103l_A,protein,167.0,T4 LYSOZYME,103l,A,T4 LYSOZYME
15,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSAA...,104l_A,protein,166.0,T4 LYSOZYME,104l,A,T4 LYSOZYME
16,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSAA...,104l_B,protein,166.0,T4 LYSOZYME,104l,B,T4 LYSOZYME
30,MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKGEL...,107l_A,protein,164.0,T4 LYSOZYME,107l,A,T4 LYSOZYME

LYSOZYME C                                                               1013
LYSOZYME                                                                  717
T4 LYSOZYME                                                               241
PROTEIN (LYSOZYME)                                                         81
HEN EGG WHITE LYSOZYME                                                     62
TAIL-ASSOCIATED LYSOZYME                                                   45
HUMAN LYSOZYME                                                             24
LYSOZYME-LIKE CHITINOLYTIC ENZYME                                          20
LYSOZYME BINDING IG KAPPA CHAIN V23-J2 REGION                              18
IG VH,ANTI-LYSOZYME                                                        15
PUTATIVE TAIL LYSOZYME                                                     12
ANTI-HEN EGG WHITE LYSOZYME MONOCLONAL ANTIBODY D1.3                       10
C-X-C CHEMOKINE RECEPTOR TYPE 4, LYSOZYME CHIMERA                           9
PROTEIN (T4 LYSOZYME)                                                       8
INHIBITOR OF VERTEBRATE LYSOZYME                                            8
GOOSE-TYPE LYSOZYME 1                                                       8
FUSION PROTEIN OF BETA-2 ADRENERGIC RECEPTOR AND T4 LYSOZYME                8
TURKEY EGG WHITE LYSOZYME                                                   6
CHIMERA OF THROMBIN CLEAVAGE SITE, TAIL-ASSOCIATED LYSOZYME, FIBRITIN       6
ANTI-LYSOZYME ANTIBODY FV REGION                                            6
Name: label, dtype: int64

In [251]:
df_polymerase = df[df['label'].str.contains('POLYMERASE', case=False)]
print(f'df_polymerase.shape: {df_polymerase.shape}')
print(f'df_polymerase.label.nunique(): {df_polymerase["label"].nunique()}')
display(df_polymerase.head(5))

df_polymerase.shape: (14065, 8)
df_polymerase.label.nunique(): 504

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
484,MSNTLFDDIFQVSEVDPGRYNKVCRIEAASTTQDQCKLTLDINVEL...,1a1d_A,protein,146,RNA POLYMERASE,1a1d,A,RNA POLYMERASE
545,ALTVSAGTKSKLAKPIQDLIKMIFDVESMKKAMVEFEIDLQKMPLG...,1a26_A,protein,361,POLY (ADP-RIBOSE) POLYMERASE,1a26,A,POLY (ADP-RIBOSE) POLYMERASE
2216,MNTINIAKNDFSDIELAAIPFNTLADHYGERLAREQLALEHESYEM...,1aro_P,protein,883,T7 RNA POLYMERASE,1aro,P,T7 RNA POLYMERASE
3349,MKLSKDTIAILKNFASINSGILLSQGKFIMTRAVNGTTYAEANISD...,1b8h_A,protein,228,DNA POLYMERASE PROCESSIVITY COMPONENT,1b8h,A,DNA POLYMERASE PROCESSIVITY COMPONENT
3350,MKLSKDTIAILKNFASINSGILLSQGKFIMTRAVNGTTYAEANISD...,1b8h_B,protein,228,DNA POLYMERASE PROCESSIVITY COMPONENT,1b8h,B,DNA POLYMERASE PROCESSIVITY COMPONENT

In [242]:
df_polymerase.label.value_counts().head(20)

DNA-DIRECTED RNA POLYMERASE SUBUNIT ALPHA                     1008
DNA-DIRECTED RNA POLYMERASE SUBUNIT BETA                       602
DNA-DIRECTED RNA POLYMERASE SUBUNIT BETA'                      493
DNA-DIRECTED RNA POLYMERASE SUBUNIT OMEGA                      468
RNA-DIRECTED RNA POLYMERASE                                    415
DNA POLYMERASE BETA                                            354
DNA POLYMERASE                                                 312
POLYMERASE ACIDIC PROTEIN                                      264
DNA POLYMERASE IV                                              262
DNA-DIRECTED RNA POLYMERASES I, II, AND III SUBUNIT RPABC3     260
DNA POLYMERASE ETA                                             231
DNA-DIRECTED RNA POLYMERASES I, II, AND III SUBUNIT RPABC5     214
DNA-DIRECTED RNA POLYMERASES I, II, AND III SUBUNIT RPABC1     203
POLY [ADP-RIBOSE] POLYMERASE 1                                 196
DNA-DIRECTED RNA POLYMERASES I, II, AND III SUBUNIT RPABC2     194
DNA-DIRECTED RNA POLYMERASE II SUBUNIT RPB3                    192
DNA-DIRECTED RNA POLYMERASE II SUBUNIT RPB9                    191
DNA-DIRECTED RNA POLYMERASES I, II, AND III SUBUNIT RPABC4     189
DNA-DIRECTED RNA POLYMERASE II SUBUNIT RPB1                    168
DNA POLYMERASE III SUBUNIT BETA                                164
Name: label, dtype: int64

In [244]:
print(f'df_polymerase.shape: {df_polymerase.shape}')

df_dna_dir_polymerase = df_polymerase[df_polymerase['label'].str.contains('DNA-DIRECTED RNA POLYMERASE', case=False)]
print(f'df_dna_dir_polymerase.shape: {df_dna_dir_polymerase.shape}')
print(f'df_dna_dir_polymerase.label.nunique(): {df_dna_dir_polymerase["label"].nunique()}')
display(df_dna_dir_polymerase.head(5))

df_rna_dir_polymerase = df_polymerase[df_polymerase['label'].str.contains('RNA-DIRECTED RNA POLYMERASE', case=False)]
print(f'df_rna_dir_polymerase.shape: {df_rna_dir_polymerase.shape}')
print(f'df_rna_dir_polymerase.label.nunique(): {df_rna_dir_polymerase["label"].nunique()}')
display(df_rna_dir_polymerase.head(5))

df_polymerase.shape: (14065, 8)
df_dna_dir_polymerase.shape: (6950, 8)
df_dna_dir_polymerase.label.nunique(): 201

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
9718,MDQENERNISRLWRAFRTVKEMVKDRGYFITQEEVELPLEDFKAKY...,1dzf_A,protein,215,"DNA-DIRECTED RNA POLYMERASES I, II, AND III SU...",1dzf,A,"DNA-DIRECTED RNA POLYMERASES I, II, AND III SU..."
10781,MIPVRCLSCGKPVSAYFNEYQRRVADGEDPKDVLDDLGLKRYCCRR...,1ef4_A,protein,55,DNA-DIRECTED RNA POLYMERASE,1ef4,A,DNA-DIRECTED RNA POLYMERASE
16890,MYKILEIADVVKVPPEEFGKDLKETVKKILMEKYEGRLDKDVGFVL...,1go3_E,protein,187,DNA-DIRECTED RNA POLYMERASE SUBUNIT E,1go3,E,DNA-DIRECTED RNA POLYMERASE SUBUNIT E
16891,MYKILEIADVVKVPPEEFGKDLKETVKKILMEKYEGRLDKDVGFVL...,1go3_M,protein,187,DNA-DIRECTED RNA POLYMERASE SUBUNIT E,1go3,M,DNA-DIRECTED RNA POLYMERASE SUBUNIT E
16892,MIGKKILGERYVTVSEAAEIMYNRAQIGELSYEQGCALDYLQKFAK...,1go3_F,protein,107,DNA-DIRECTED RNA POLYMERASE SUBUNIT F,1go3,F,DNA-DIRECTED RNA POLYMERASE SUBUNIT F

df_rna_dir_polymerase.shape: (744, 8)
df_rna_dir_polymerase.label.nunique(): 18

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
17734,SMSYTWTGALITPCAAEESKLPINALSNSLLRHHNMVYATTSRSAG...,1gx5_A,protein,536,RNA-DIRECTED RNA POLYMERASE,1gx5,A,RNA-DIRECTED RNA POLYMERASE
17735,SMSYTWTGALITPCAAEESKLPINALSNSLLRHHNMVYATTSRSAG...,1gx6_A,protein,531,RNA-DIRECTED RNA POLYMERASE,1gx6,A,RNA-DIRECTED RNA POLYMERASE
19368,PRRAPAFPLSDIKAQMLFANNIKAQQASKRSFKEGAIETYEGLLSV...,1hhs_A,protein,664,RNA-DIRECTED RNA POLYMERASE,1hhs,A,RNA-DIRECTED RNA POLYMERASE
19369,PRRAPAFPLSDIKAQMLFANNIKAQQASKRSFKEGAIETYEGLLSV...,1hhs_B,protein,664,RNA-DIRECTED RNA POLYMERASE,1hhs,B,RNA-DIRECTED RNA POLYMERASE
19370,PRRAPAFPLSDIKAQMLFANNIKAQQASKRSFKEGAIETYEGLLSV...,1hhs_C,protein,664,RNA-DIRECTED RNA POLYMERASE,1hhs,C,RNA-DIRECTED RNA POLYMERASE

In [250]:
df.loc[df['label'].str.contains('RNA-DIRECTED RNA POLYMERASE', case=False), 'label'] = 'RNA_DIRECTED_RNA_POLYMERASE'
df.loc[df['label'].str.contains('DNA-DIRECTED RNA POLYMERASE', case=False), 'label'] = 'DNA_DIRECTED_RNA_POLYMERASE'

df['label'].value_counts().head(20)

RIBOSOMAL                                                          84768
HEAVY CHAIN                                                        11495
LIGHT CHAIN                                                        10834
DNA_DIRECTED_RNA_POLYMERASE                                         6950
CAPSID PROTEIN                                                      5335
COAT PROTEIN                                                        4587
SPIKE GLYCOPROTEIN                                                  2634
UNCHARACTERIZED PROTEIN                                             2177
CAPSID PROTEIN VP1                                                  2158
MAJOR CAPSID PROTEIN                                                2115
BETA-2-MICROGLOBULIN                                                2091
BETA-LACTAMASE                                                      1532
HEMAGGLUTININ                                                       1321
ATP-DEPENDENT CLP PROTEASE PROTEOLYTIC SUBUNIT                      1288
HISTONE H4                                                          1276
CAMP AND CAMP-INHIBITED CGMP 3',5'-CYCLIC PHOSPHODIESTERASE 10A     1151
B-PHYCOERYTHRIN BETA CHAIN                                          1106
6,7-DIMETHYL-8-RIBITYLLUMAZINE SYNTHASE                             1045
PHYCOERYTHRIN ALPHA SUBUNIT                                         1044
LYSOZYME C                                                          1013
Name: label, dtype: int64

In [252]:

df_capsid = df[df['label'].str.contains(' CAPSID', case=False)]
print(f'df_capsid.shape: {df_capsid.shape}')
print(f'df_capsid.label.nunique(): {df_capsid["label"].nunique()}')
display(df_capsid.head(5))

df_histone = df[df['label'].str.contains('histone', case=False)]
print(f'df_histone.shape: {df_histone.shape}')
print(f'df_histone.label.nunique(): {df_histone["label"].nunique()}')
display(df_histone.head(5))

df_capsid.shape: (5684, 8)
df_capsid.label.nunique(): 186

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
678,VKAETRLNPDLQPTEX,1a3r_P,protein,16,HUMAN RHINOVIRUS CAPSID PROTEIN VP2,1a3r,P,HUMAN RHINOVIRUS CAPSID PROTEIN VP2
693,MSPTSILDIRQGPKEPFRDYVDRFYKTLRAEQASQEVKNWMTETLL...,1a43_A,protein,87,HIV-1 CAPSID,1a43,A,HIV-1 CAPSID
866,AVTVVPDPTCCGTLSFKVPKDAKKGKHLGTFDIRQAIMDYGGLHSQ...,1a6c_A,protein,513,TOBACCO RINGSPOT VIRUS CAPSID PROTEIN,1a6c,A,TOBACCO RINGSPOT VIRUS CAPSID PROTEIN
1030,MDIRQGPKEPFRDYVDRFYKTLRAEQASQEVKNWMTETLLVQNANP...,1a8o_A,protein,70,HIV CAPSID,1a8o,A,HIV CAPSID
1441,PIVQNLQGQMVHQAISPRTLNAWVKVVEEKAFSPEVIPMFSALSEG...,1afv_A,protein,151,HUMAN IMMUNODEFICIENCY VIRUS TYPE 1 CAPSID PRO...,1afv,A,HUMAN IMMUNODEFICIENCY VIRUS TYPE 1 CAPSID PRO...

df_histone.shape: (7775, 8)
df_histone.label.nunique(): 428

,sequence,pdb_id,mol,length,mol_description,id_pdb,subunit,label
977,MELPIAPIGRIIKDAGAERVSDDARITLAKILEEMGRDIASEAIKL...,1a7w_A,protein,69,HISTONE HMFB,1a7w,A,HISTONE HMFB
1977,LATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKL...,1aoi_A,protein,116,HISTONE H3,1aoi,A,HISTONE H3
1978,LATKAARKSAPATGGVKKPHRYRPGTVALREIRRYQKSTELLIRKL...,1aoi_E,protein,116,HISTONE H3,1aoi,E,HISTONE H3
1979,KRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVF...,1aoi_B,protein,87,HISTONE H4,1aoi,B,HISTONE H4
1980,KRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVF...,1aoi_F,protein,87,HISTONE H4,1aoi,F,HISTONE H4

In [254]:
display(df_capsid['label'].value_counts().head(20))
display(df_histone['label'].value_counts().head(20))

MAJOR CAPSID PROTEIN                                      2115
HIV-1 CAPSID PROTEIN                                       421
MAJOR CAPSID PROTEIN L1                                    253
TRIPLEX CAPSID PROTEIN 2                                   188
SMALL OUTER CAPSID PROTEIN                                 183
PHAGE MAJOR CAPSID PROTEIN, HK97 FAMILY                    174
MAJOR CAPSID PROTEIN VP1                                   169
INTERMEDIATE CAPSID PROTEIN VP6                            143
PENAEUS MONODON METALLODENSOVIRUS MAJOR CAPSID PROTEIN     120
VP1 CAPSID                                                 120
OUTER CAPSID PROTEIN VP4                                   116
OUTER CAPSID GLYCOPROTEIN VP7                              104
TRIPLEX CAPSID PROTEIN 1                                    94
MINOR CAPSID PROTEIN A1                                     90
MAJOR CAPSID PROTEIN (MCP)                                  72
INNER CAPSID PROTEIN VP2                                    64
PUTATIVE CAPSID PROTEIN                                     62
MAJOR CAPSID PROTEIN RCC01687                               61
ECHOVIRUS 18 CAPSID PROTEIN 1                               52
ECHOVIRUS 18 CAPSID PROTEIN 2                               52
Name: label, dtype: int64

HISTONE H4                                                   1276
HISTONE H2A TYPE 1-B/E                                        446
HISTONE H3.1                                                  435
HISTONE H3.2                                                  433
HISTONE H2A                                                   370
HISTONE H2B TYPE 1-J                                          338
HISTONE H3                                                    328
HISTONE H2B 1.1                                               302
HISTONE-ARGININE METHYLTRANSFERASE CARM1                      273
HISTONE H2B TYPE 1-K                                          153
HISTONE DEACETYLASE 8                                         143
HISTONE H2B                                                   141
HISTONE H2A TYPE 1                                            138
HISTONE H3.3                                                  112
HISTONE DEACETYLASE 2                                         105
HISTONE DEACETYLASE                                            92
LYSINE-SPECIFIC HISTONE DEMETHYLASE 1A                         76
HISTONE ACETYLTRANSFERASE P300                                 68
HISTONE-LYSINE N-METHYLTRANSFERASE, H3 LYSINE-79 SPECIFIC      67
HISTONE H2B TYPE 1-C/E/F/G/I                                   65
Name: label, dtype: int64

In [ ]:
df.loc[df['label'].str.contains(' CAPSID', case=False), 'label'] = 'CAPSID'
df.loc[df['label'].str.contains('HISTONE', case=False), 'label'] = 'HISTONE'

df['label'].value_counts().head(20)

In [ ]:
df_ribosomes['label']

In [ ]:
df['mol_description'].value_counts().tail(50)

PHYR SIGMA-LIKE DOMAIN                                                                 1
NEPR ANTI SIGMA FACTOR                                                                 1
AURELIN                                                                                1
SENSOR PROTEIN VRAS                                                                    1
LACTOCOCCIN 972                                                                        1
DNAJ HOMOLOG SUBFAMILY B MEMBER 2                                                      1
UNCHARACTERIZED PROTEIN ORF47                                                          1
CP12 DOMAIN-CONTAINING PROTEIN 2                                                       1
F-BOX/LRR-REPEAT PROTEIN 2                                                             1
CDT-LPS                                                                                1
ALVINELLACIN                                                                           1
UNCHARACTERIZED PROTEIN YJDK                                                           1
ANTI-CD28XCD3 CODV FAB HEAVY CHAIN                                                     1
ANTI-CD28XCD3 CODV FAB LIGHT CHAIN                                                     1
ANTI-CD28XCD3 CODV-FAB LIGHT CHAIN                                                     1
ANTI-CD28XCD3 CODV-FAB HEAVY CHAIN                                                     1
AF4/FMR2 FAMILY MEMBER 1/PROTEIN AF-9 CHIMERA                                          1
TCR HY.1B11 ALPHA CHAIN                                                                1
BLO T 21 ALLERGEN                                                                      1
VHH ANTIBODY V6H8                                                                      1
THP5 PEPTIDE                                                                           1
PROSPERO HOMEOBOX PROTEIN 1                                                            1
AMINODEOXYCHORISMATE SYNTHASE                                                          1
EXOCRINE GLAND-SECRETING PEPTIDE 1                                                     1
PUTATIVE ACYL CARRIER PROTEIN                                                          1
CONOTOXIN IM17A                                                                        1
DE NOVO DESIGNED PROTEIN OR135                                                         1
COPRISIN                                                                               1
LAMIN-B2                                                                               1
CYCLIN-D-BINDING MYB-LIKE TRANSCRIPTION FACTOR 1                                       1
TCR HY.1B11 BETA CHAIN                                                                 1
CHEMOTAXIS PROTEIN CHEY, IMIDAZOLE GLYCEROL PHOSPHATE SYNTHASE SUBUNIT HISF CHIMERA    1
DOUBLE-STRANDED RNA-SPECIFIC EDITASE ADAR                                              1
PROTEIN C17ORF37                                                                       1
ACYL-COA SYNTHETASE (AMP-FORMING)/AMP-ACID LIGASE II-LIKE PROTEIN                      1
BETA-2 ADRENERGIC RECEPTOR,LYSOZYME,BETA-2 ADRENERGIC RECEPTOR                         1
ALR2454 PROTEIN                                                                        1
NEUROTOXIN MEUNATX-5                                                                   1
IMMUNOGLOBULIN LAMBDA-LIKE POLYPEPTIDE 1                                               1
NEUROTENSIN 8-13                                                                       1
GRXS14                                                                                 1
NEUROTENSIN RECEPTOR TYPE 1, LYSOZYME CHIMERA                                          1
PITUITARY HOMEOBOX 3                                                                   1
MUCIN-LIKE PROTOCADHERIN                                                               1
POLY(ALANINE) SUBSTRATE                                                                1
U1-TRTX-SP1A                                                                           1
MANNOSE-6-PHOSPHATE/INSULIN-LIKE GROWTH FACTOR II RECEPTOR                             1
LUCIFENSIN                                                                             1
FAB 2 HEAVY CHAIN                                                                      1
MFS-BOUND SANS CEN2 PEPTIDE                                                            1
Name: mol_description, dtype: int64

In [ ]:
aminos = ['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y']
for letter in aminos:
    df_train[letter] = df_train.protein_sequence.str.count(letter)
    df_test[letter] = df_test.protein_sequence.str.count(letter)

[table of amino acid physical properties](https://www.thermofisher.com/ca/en/home/life-science/protein-biology/protein-biology-learning-center/protein-biology-resource-library/pierce-protein-methods/amino-acid-physical-properties.html)

In [29]:
df_aa = pd.read_csv('../research/aa_phys_properties.csv')
df_aa

,Amino Acid,Code,Hydropathy,Charge,pKa NH2,pKa COOH,pK(R),Solubility
0,Arginine,R,hydrophilic,+,9.09,2.18,13.2,71.8
1,Asparagine,N,hydrophilic,N,8.80,2.02,,2.4
2,Aspartate,D,hydrophilic,-,9.60,1.88,3.65,0.42
3,Glutamate,E,hydrophilic,-,9.67,2.19,4.25,0.72
4,Glutamine,Q,hydrophilic,N,9.13,2.17,,2.6
5,Lysine,K,hydrophilic,+,10.28,8.90,2.2,NaN
6,Serine,S,hydrophilic,N,9.15,2.21,,36.2
7,Threonine,T,hydrophilic,N,9.12,2.15,,freely
8,Cysteine,C,moderate,N,10.78,1.71,8.33,freely
9,Histidine,H,moderate,+,8.97,1.78,6,4.19
10,Methionine,M,moderate,N,9.21,2.28,,5.14
11,Alanine,A,hydrophobic,N,9.87,2.35,,15.8
12,Valine,V,hydrophobic,N,9.72,2.29,,5.6
13,Glycine,G,hydrophobic,N,9.60,2.34,,22.5
14,Isoleucine,I,hydrophobic,N,9.76,2.32,,3.36
15,Leucine,L,hydrophobic,N,9.60,2.36,,2.37
16,Phenylalanine,F,hydrophobic,N,9.24,2.58,,2.7
17,Proline,P,hydrophobic,N,10.60,1.99,,1.54
18,Tryptophan,W,hydrophobic,N,9.39,2.38,,1.06
19,Tyrosine,Y,hydrophobic,N,9.11,2.20,10.1,0.038